(* ::Package:: *)

(* Yi Wang, 2013, tririverwangyi@gmail.com, GPLv3 *)
BeginPackage["MathGR`typeset`", {"MathGR`tensor`"}]

ToTeXString::usage="ToTeXString[expr] translates expr into TeXForm and return the result in a string"
ToTeX::usage="ToTeX[expr] prints expr into TeXForm"
ToTeXHook::usage="ToTeXHook is set of transformations before export to TeX"
ToTeXTemplate::usage="ToTeXTemplate = True (default, export header and tail of tex) or False (no header or tail, only the equation)."
DecorateTeXString::usage="DecorateTeXString[s] does post processing for a TeX string."
Begin["`Private`"]
Needs["MathGR`utilPrivate`"]


(* ::Section:: *)
(* TraditionalForm and TeX output *)


altUp:= Alternatives @@ IdxUpList
altDn:= Alternatives @@ IdxDnList
idxQ[idx__]:= MatchQ[{idx}, {(IdxPtn|_UE|_DE) ..}]
makeBoxesTsrQ = !MatchQ[#, List|Rule|Alternatives|Sequence]&
mkPd[form_][i___] := Sequence @@ (MakeBoxes[\[CapitalSampi]@#, form] & /@ {i})

(*SetOptions[$Output, PageWidth -> 200]*)
If[!defQ@ToTeXHook, ToTeXHook = {}]
	
removeTextAndCurly[s_String]:= s // StringReplace[#, "\\text{"~~f__~~"}"/;StringFreeQ[f,{"{","}"}] :>f ] & // StringReplace[#, "$":>""] &
removeWaste[s_String]:= s // StringReplace[#, "\\text{}" :> "{}"] & // StringReplace[#, "){}^" :> ")^"] & // StringReplace[#, "\\partial {}_" :> "\\partial_"] &
replaceTimeDot[s_String]:= If[!StringFreeQ[s, "\\partial ^{-2}"], s (* dot acting on Pm2 looks wrong *),
	StringReplace[s, {"\\partial_0\\partial_0\\partial_0" :> "\\dddot", "\\partial_0\\partial_0" :> "\\ddot", "\\partial_0" :> "\\dot"}]]
breakLine[s_String]:= s // StringReplace[#, {"+":>"\n + ", f_~~"-" /; f=!="\n"&&f=!="{" :> f<>"\n - ", "=":>"\n= ", "\\to":>"\n \\to "}] &
addHeaderTail[s_String]:= If[!ToTeXTemplate, s, Print["Hint: set ToTeXTemplate = False to output equation only."]; "%Generated by MathGR/typeset.m, "<>DateString[]<>
	".\n\\documentclass{revtex4}\n\\usepackage{breqn}\n\\begin{document}\n\\begin{dmath}\n"<>s<>"\n\\end{dmath}\n\\end{document}\n"]
finalCleanUp[s_String]:= s // StringReplace[#, {"\n\n"->"\n"}] & (* Shouldn't be necessary. Just in case. *)

If[!defQ@DecorateTeXString, DecorateTeXString = (# // removeWaste // replaceTimeDot // removeTextAndCurly // breakLine // addHeaderTail // finalCleanUp) & ]

If[!defQ[ToTeXTemplate], ToTeXTemplate = True]
ToTeXString[e_]:= e//.ToTeXHook // PolynomialForm[#, TraditionalOrder -> False]& // ToString[#, TeXForm] & // DecorateTeXString
ToTeX[e_] := ToTeXString[e] // Print

MakeBoxes[\[CapitalSampi], TraditionalForm]:="\[PartialD]"
MakeBoxes[Dta, TraditionalForm]:="\[Delta]"
MakeBoxes[tsr_[idx__], TraditionalForm]/;(idxQ[idx]&&makeBoxesTsrQ[tsr]):= With[
	{idList={idx}/.{altUp[i_]:>SuperscriptBox["", i], UE[i_]:>SuperscriptBox["", ToString@i], altDn[i_]:>SubscriptBox["", i], DE[i_]:>SubscriptBox["", ToString@i]}},
	TagBox[RowBox[{MakeBoxes[tsr, TraditionalForm]}~Join~idList],  "mgrTsr", SyntaxForm->"symbol"]]
MakeBoxes[PdT[f_, PdVars[i0:DE@0..., i__]], TraditionalForm] /; FreeQ[{i}, DE@0] := With[{id0 = mkPd[TraditionalForm]@i0, id = mkPd[TraditionalForm]@i}, 
	TagBox[RowBox[{id, id0, MakeBoxes[f, TraditionalForm]}], "mgrPdT", SyntaxForm -> "^"]]
MakeBoxes[PdT[f_, PdVars[i0:DE@0..]], TraditionalForm] := With[{id0 = mkPd[TraditionalForm]@i0}, 
	TagBox[RowBox[{id0, MakeBoxes[f, TraditionalForm]}], "mgrPdT", SyntaxForm -> "symbol"]]


(* ::Section:: *)
(* All the below only run with a frontend *)


If[$FrontEnd===Null, Print["(typeset.m): No FrontEnd detected. StandardForm and input aliases definitions skipped."],












(* ::Section:: *)
(* Tensor *)


(*
MakeBoxes[tsr_[idx__], StandardForm]/;(idxQ[idx]&&makeBoxesTsrQ[tsr]):= TagBox[RowBox[{AdjustmentBox[MakeBoxes[tsr, StandardForm], BoxMargins -> {{0, -0.2}, {0, 0}}], 
	StyleBox[ GridBox[{idx} /. {
		{(a:altUp)[i_]:>TagBox[StyleBox[MakeBoxes[i, StandardForm], FontColor->IdxColor@a], a], 
			IdxDnPtn:>"", UE@n_:>TagBox[StyleBox[MakeBoxes[n, StandardForm], FontColor->IdxColor@UE],UE], DE@n_:>""}, 
		{IdxUpPtn:>"", (a:altDn)[i_]:>TagBox[StyleBox[MakeBoxes[i, StandardForm], FontColor->IdxColor@a], a], 
			DE@n_:>TagBox[StyleBox[MakeBoxes[n, StandardForm], FontColor->IdxColor@DE],DE], UE@n_:>""}
	}, ColumnSpacings->0, RowSpacings->0], FontSize->10]}], "mgrTsr"(*, SyntaxForm->"symbol"*)];
parseUD[lst_, StandardForm]:= Sequence @@ (Map[If[#[[1]] === "", #[[2]], #[[1]]] &, Transpose[lst]] /. {TagBox[i_ | StyleBox[i_, __], tag_] :> tag@ToExpression[i, StandardForm]});
MakeExpression[TagBox[RowBox[{AdjustmentBox[t_, ___], StyleBox[GridBox[idx__, ___], ___]}], "mgrTsr", OptionsPattern[]], StandardForm] := 
	With[{h = ToExpression[t, StandardForm], i = parseUD[idx, StandardForm]}, HoldComplete@h@i];
*)

(* The new box form has advantages: (1) Uniform look in input/output/code blocks/pdf. (2) Robust against edit/copy-paste. Not possible to leave imcomplete boxes. (3) No longer additional brackets. *)
MakeBoxes[tsr_[idx__], StandardForm]/;(idxQ[idx]&&makeBoxesTsrQ[tsr]):= TagBox[GridBox[{{GridBox[{{MakeBoxes[tsr, StandardForm]}}, Selectable->True], 
	GridBox[{idx} /. {
		{(a:altUp)[i_]:>StyleBox[TagBox[GridBox[{{MakeBoxes[i, StandardForm]}}, Selectable->True], a], FontColor->IdxColor@a, FontSize->10], 
			IdxDnPtn:>"", UE@n_:>StyleBox[TagBox[GridBox[{{MakeBoxes[n, StandardForm]}}, Selectable->True],UE], FontColor->IdxColor@UE, FontSize->10], DE@n_:>""}, 
		{IdxUpPtn:>"", (a:altDn)[i_]:>StyleBox[TagBox[GridBox[{{MakeBoxes[i, StandardForm]}}, Selectable->True], a], FontColor->IdxColor@a, FontSize->10], 
			DE@n_:>StyleBox[TagBox[GridBox[{{MakeBoxes[n, StandardForm]}}, Selectable->True],DE], FontColor->IdxColor@DE, FontSize->10], UE@n_:>""}
	}, ColumnSpacings->0, RowSpacings->-0.5]}}, ColumnSpacings->0, RowSpacings->0, Selectable->False], "mgrTensor", SyntaxForm->"symbol", Selectable->False];

parseId[lst_, StandardForm]:= Sequence @@ (Map[If[#[[1]] === "", #[[2]], #[[1]]] &, Transpose[lst]] 
	/. {StyleBox[TagBox[GridBox[{{i_}},___] , tag_,___], ___] | TagBox[GridBox[{{i_}},___] , tag_,___] :> tag@ToExpression[i, StandardForm]});
MakeExpression[TagBox[GridBox[{{GridBox[{{t_}}, ___], GridBox[idx__, ___]}},___], "mgrTensor", ___], StandardForm] := 
	With[{h = ToExpression[t, StandardForm], i = parseId[idx, StandardForm]}, HoldComplete@h@i];


(* ::Section:: *)
(* Derivative *)


(*
MakeBoxes[PdT[f_, PdVars[i__]], StandardForm] /; FreeQ[{i}, DE@0] || !FreeQ[{f}, Pm2] := 
	With[{id = mkPd[StandardForm]@i}, TagBox[GridBox[{{id, GridBox[{{MakeBoxes[f, StandardForm]}},Selectable\[Rule]True]}}, ColumnSpacings->0, RowSpacings->0], "mgrPd", SyntaxForm -> "^", Selectable\[Rule]False]];
MakeBoxes[PdT[a_, PdVars[dt : DE@0 .., i__]], StandardForm] /; FreeQ[{i}, DE@0]:= With[{id = mkPd[StandardForm]@i, bu = StringJoin@ConstantArray["\[Bullet]", Length@{dt}]}, 
	TagBox[GridBox[{{id, GridBox[{{OverscriptBox[MakeBoxes[a, StandardForm], bu]}},Selectable\[Rule]True]}}, ColumnSpacings->0, RowSpacings->0], "mgrPd", SyntaxForm -> "^", Selectable\[Rule]False]];
MakeBoxes[PdT[a_, PdVars[dt : DE@0 ..]], StandardForm] /; FreeQ[{a}, Pm2] := With[{bu = StringJoin@ConstantArray["\[Bullet]", Length@{dt}]}, OverscriptBox[MakeBoxes[a, StandardForm], bu]];

MakeExpression[TagBox[GridBox[{{d__,GridBox[{{f_}},___]}},___], "mgrPd", ___], StandardForm]:= 
	With[{idExpr=PdVars@@Cases[ToExpression[{d}, StandardForm], \[CapitalSampi][a_]:>a], fExpr=ToExpression[f, StandardForm]}, HoldComplete@PdT[fExpr, idExpr]];

MakeExpression[TagBox[GridBox[{{d__,GridBox[{{f_}},___]}},___], "mgrPd", ___], StandardForm]:= 
	With[{idExpr=ToExpression/@{d}, fExpr=ToExpression[f, StandardForm]}, HoldComplete@PdT[fExpr, idExpr]];

MakeExpression[OverscriptBox[a_, str_String], StandardForm] := With[{pds = Nest[Pd[#, DE@0] &, ToExpression[a, StandardForm], 
      StringLength[str]]}, HoldComplete[pds]] /; StringMatchQ[str, "\[Bullet]" ..];

MakeBoxes[Pm2[a_, type_], form_] := TagBox[RowBox[{TagBox[StyleBox[SuperscriptBox[MakeBoxes[\[CapitalSampi], form], "-2"], FontColor->IdxColor[type]], type], 
	"(", MakeBoxes[a, form], ")" }], "mgrPm2"];
MakeExpression[TagBox[RowBox[{TagBox[_, type_], "(", a_, ")"}], "mgrPm2"], StandardForm]:= With[{expr=Pm2[ToExpression[a, StandardForm], type]}, HoldComplete[expr]];
*)


(*
MakeBoxes[PdT[f_, PdVars[i__]], StandardForm] /; FreeQ[{i}, DE@0] || !FreeQ[{f}, Pm2] := 
	With[{id = mkPd[StandardForm]@i}, TagBox[RowBox[{id, MakeBoxes[f, StandardForm]}], "mgrPd", Selectable->False]];
MakeBoxes[PdT[a_, PdVars[dt : DE@0 .., i__]], StandardForm] /; FreeQ[{i}, DE@0]:= With[{id = mkPd[StandardForm]@i, bu = StringJoin@ConstantArray["\[Bullet]", Length@{dt}]}, 
	TagBox[RowBox[{id, OverscriptBox[MakeBoxes[a, StandardForm], bu]}], "mgrPd", Selectable->False]];
MakeBoxes[PdT[a_, PdVars[dt : DE@0 ..]], StandardForm] /; FreeQ[{a}, Pm2] := With[{bu = StringJoin@ConstantArray["\[Bullet]", Length@{dt}]}, OverscriptBox[MakeBoxes[a, StandardForm], bu]];

MakeExpression[TagBox[RowBox[{d__,f_}], "mgrPd", ___], StandardForm]:= 
	With[{idExpr=PdVars@@Cases[ToExpression[{d}, StandardForm], \[CapitalSampi][a_]:>a], fExpr=ToExpression[f, StandardForm]}, HoldComplete@PdT[fExpr, idExpr]];

MakeExpression[OverscriptBox[a_, str_String], StandardForm] := With[{pds = Nest[Pd[#, DE@0] &, ToExpression[a, StandardForm], 
      StringLength[str]]}, HoldComplete[pds]] /; StringMatchQ[str, "\[Bullet]" ..];

MakeBoxes[Pm2[a_, type_], form_] := TagBox[RowBox[{TagBox[StyleBox[SuperscriptBox[MakeBoxes[\[CapitalSampi], form], "-2"], FontColor->IdxColor[type]], type], 
	"(", MakeBoxes[a, form], ")" }], "mgrPm2", Selectable->False];
MakeExpression[TagBox[RowBox[{TagBox[_, type_], "(", a_, ")"}], "mgrPm2",___], StandardForm]:= With[{expr=Pm2[ToExpression[a, StandardForm], type]}, HoldComplete[expr]];
*)


MakeBoxes[\[CapitalSampi], StandardForm]:= TagBox["\[PartialD]", "mgrSa", Selectable->False];
MakeExpression[TagBox["\[PartialD]","mgrSa",___], StandardForm]:= HoldComplete@\[CapitalSampi];

MakeBoxes[PdT[f_, PdVars[i__]], StandardForm] /; FreeQ[{i}, DE@0] || !FreeQ[{f}, Pm2] := 
	With[{id = mkPd[StandardForm]@i}, TagBox[RowBox[{GridBox[{{id, GridBox[{{MakeBoxes[f, StandardForm]}},Selectable->True]}}, ColumnSpacings->0, RowSpacings->0],""}], "mgrPd", Selectable->False]];
MakeBoxes[PdT[a_, PdVars[dt : DE@0 .., i__]], StandardForm] /; FreeQ[{i}, DE@0]:= With[{id = mkPd[StandardForm]@i, bu = StringJoin@ConstantArray["\[Bullet]", Length@{dt}]}, 
	TagBox[RowBox[{GridBox[{{id, GridBox[{{OverscriptBox[MakeBoxes[a, StandardForm], bu]}},Selectable->True]}}, ColumnSpacings->0, RowSpacings->0],""}], "mgrPd", Selectable->False]];
MakeBoxes[PdT[a_, PdVars[dt : DE@0 ..]], StandardForm] /; FreeQ[{a}, Pm2] := With[{bu = StringJoin@ConstantArray["\[Bullet]", Length@{dt}]}, OverscriptBox[MakeBoxes[a, StandardForm], bu]];

MakeExpression[TagBox[GridBox[{{d__,GridBox[{{f_}},___]}},___], "mgrPd", ___], StandardForm]:= 
	With[{idExpr=PdVars@@Cases[ToExpression[{d}, StandardForm], \[CapitalSampi][a_]:>a], fExpr=ToExpression[f, StandardForm]}, HoldComplete@PdT[fExpr, idExpr]];

MakeExpression[OverscriptBox[a_, str_String], StandardForm] := With[{pds = Nest[Pd[#, DE@0] &, ToExpression[a, StandardForm], 
      StringLength[str]]}, HoldComplete[pds]] /; StringMatchQ[str, "\[Bullet]" ..];

MakeBoxes[Pm2[a_, type_], form_] := TagBox[RowBox[{TagBox[StyleBox[SuperscriptBox[MakeBoxes[\[CapitalSampi], form], "-2"], FontColor->IdxColor[type]], type], 
	"(", MakeBoxes[a, form], ")" }], "mgrPm2", Selectable->False];
MakeExpression[TagBox[RowBox[{TagBox[_, type_], "(", a_, ")"}], "mgrPm2",___], StandardForm]:= With[{expr=Pm2[ToExpression[a, StandardForm], type]}, HoldComplete[expr]];


(* ::Section:: *)
(* Paste the blob calculated in InputAliases.nb *)


aliasesList = {"tp0"->OverscriptBox["\[SelectionPlaceholder]","\[Bullet]"],
	"tu"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]]},
{""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),"td"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{""},
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),"tuu"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]], 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]]},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),"tud"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]], ""},
{"", 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),"tdu"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{"", 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]]},
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]], ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),"tdd"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{"", ""},
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]], 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),
	"tudd"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]], "", ""},
{"", 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]], 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\),"tuddd"->\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\"\<\[SelectionPlaceholder]\>\""}
},
Selectable->True], GridBox[{
{
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`UP],
FontSize->10,
FontColor->GrayLevel[0]], "", "", ""},
{"", 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]], 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]], 
StyleBox[
TagBox[GridBox[{
{"\"\<\[Placeholder]\>\""}
},
Selectable->True],
MathGR`tensor`DN],
FontSize->10,
FontColor->GrayLevel[0]]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[-0.2]}, Offset[0.2]}}]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}},
Selectable->False],
"mgrTensor",
Selectable->False,
SyntaxForm->"symbol"]\)};


addAlias[alias_]:=CurrentValue[$FrontEndSession,{InputAliases,alias[[1]]}]=alias[[2]];
addAlias/@(aliasList);



] (* end of the big if (or tell me how to stop in the middle of a package gracefully?) *)

End[]
EndPackage[]
