(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll[\[DoubleStruckD],GRETsr];


SetAttributes[DefQ, HoldAll];
DefQ[x_]:= {OwnValues[x],UpValues[x],DownValues[x]} =!= {{},{},{}};


If[!DefQ[Col],Col={Unique[]}];
If[!DefQ[Simp], Simp[e_] := Collect[e, Col, Simplify]];


If[!DefQ[\[DoubleStruckX]], Print["Please define coordinate before running GRE."];Abort[]];
If[DefQ[\[DoubleStruckD]s2], \[DoubleStruckG]Mat = Simp[Map[Coefficient[\[DoubleStruckD]s2,#[[2]]]/If[#[[1]],1,2]&,Table[{i===j,\[DoubleStruckD][i]\[DoubleStruckD][j]},{i,\[DoubleStruckX]},{j,\[DoubleStruckX]}],{2}]],
	If[DefQ[\[DoubleStruckG]Mat], \[DoubleStruckD]s2 = (Table[\[DoubleStruckD][i],{i,\[DoubleStruckX]}] . \[DoubleStruckG]Mat . Table[{\[DoubleStruckD][i]},{i,\[DoubleStruckX]}])[[1]]//Simp, 
		Print["Please define either \[DoubleStruckD]s2 or \[DoubleStruckG] before running GRE."];Abort[]]];


PdBox[lst_]:= StyleBox[#, FontSize->10]&@ GridBox[#, Selectable->True, ColumnSpacings->0, RowSpacings->0]&@ Transpose@DeleteCases[Transpose[Map[ToBoxes,lst,{2}]]/.{"1",dn_}:>{"",dn},{"0",_}];
MakeBoxes[Derivative[d__][f_][x__],StandardForm]:= TagBox[RowBox[{GridBox[{{"\[PartialD]", PdBox[{{d},{x}}],
	GridBox[{{ToBoxes@f@x}}, Selectable->True]}}, ColumnSpacings->0, RowSpacings->0],""}],"GRED", Selectable->False] /;Length[{x}]>1 && VectorQ[{d}, NumberQ] \
		&& VectorQ[{x}, AtomQ] (* to avoid formatting D[f[x+y,z+w], x] *) \
		&& Length@DeleteDuplicates@{x}===Length@{x} (* to avoid formatting D[f[x, x], x] *)


MakeExpression[TagBox[GridBox[{{"\[PartialD]", StyleBox[GridBox[{n__,x__},___],___], GridBox[{{f_}},___]}}, ___],"GRED", ___], StandardForm]:= 
	With[{h=ToExpression@f,ids=Sequence@@Transpose@Map[ToExpression,{x,n/.\!\(\*
TagBox[
StyleBox["\"\<\>\"",
ShowSpecialCharacters->False,
ShowStringCharacters->True,
NumberMarks->True],
FullForm]\)->"1"},{2}]},HoldComplete[D[h,ids]]]


MakeBoxes[GRETsr[t_,i_List],StandardForm]:=With[{
		tBox=GridBox[{{ToBoxes@t}},Selectable->True],
		iBox=StyleBox[GridBox[Map[ToBoxes,i,{2}]/.{"\[Placeholder]"->"","Null"->""}, ColumnSpacings->0, RowSpacings->0, Selectable->True],FontSize->10]},
	TagBox[GridBox[{{tBox,iBox}}, ColumnSpacings->0, RowSpacings->0],"GRETsr", Selectable->False]];

MakeExpression[TagBox[GridBox[{{GridBox[{{f_}},___],StyleBox[GridBox[i_List,___],___]}},___],"GRETsr",___],StandardForm]:=
	With[{fExpr=ToExpression@f,iExpr=Map[ToExpression,i/."\[Placeholder]"->"",{2}]}, HoldComplete@GRETsr[fExpr,iExpr]];


nonSystemFunctionPattern = HoldPattern[f_ /; Head[f]=!=Symbol || (Head[f]==Symbol && Context[f]=!="System`")];

With[{fx=(f:nonSystemFunctionPattern)@@\[DoubleStruckX]}, MakeBoxes[fx, StandardForm]:= TagBox[StyleBox[ToBoxes[f],Red],"GREFX",Selectable->False]];
MakeExpression[TagBox[f_,"GREFX",___],StandardForm]:= With[{fx=ToExpression[f]@@\[DoubleStruckX]},HoldComplete@fx];

With[{fx=(f:nonSystemFunctionPattern)[\[DoubleStruckX][[1]]]}, MakeBoxes[fx, StandardForm]:= TagBox[StyleBox[ToBoxes[f],Purple],"GREFX0",Selectable->False]];
MakeExpression[TagBox[f_,"GREFX0",___],StandardForm]:= With[{fx=ToExpression[f][\[DoubleStruckX][[1]]]},HoldComplete@fx];

With[{fx=(f:nonSystemFunctionPattern)[\[DoubleStruckX][[2]]]}, MakeBoxes[fx, StandardForm]:= TagBox[StyleBox[ToBoxes[f],Blue],"GREFX1",Selectable->False]];
MakeExpression[TagBox[f_,"GREFX1",___],StandardForm]:= With[{fx=ToExpression[f][\[DoubleStruckX][[2]]]},HoldComplete@fx];


addAlias[alias_]:=CurrentValue[$FrontEndSession,{InputAliases,alias[[1]]}]=alias[[2]];
aliasList = {
	"eu"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{0},{Null}}]],
	"ed"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{Null},{0}}]],
	"euu"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{0,0},{Null,Null}}]],
	"eud"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{0,Null},{Null,0}}]],
	"edu"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{Null,0},{0,Null}}]],
	"edd"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{Null,Null},{0,0}}]],
	"eudd"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{0,Null,Null},{Null,0,0}}]],
	"euddd"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{0,Null,Null,Null},{Null,0,0,0}}]],
	"edddd"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{Null,Null,Null,Null},{0,0,0,0}}]],
	"et"->ToBoxes[GRETsr[\[SelectionPlaceholder],{{0},{0}}]],
	"ex"->ToBoxes[\[SelectionPlaceholder]@@\[DoubleStruckX]],
	"e0"->ToBoxes[\[SelectionPlaceholder][\[DoubleStruckX][[1]]]],
	"ep"->ToBoxes[Unevaluated@D[\[Placeholder],\[SelectionPlaceholder]]]
};
addAlias/@(aliasList/."0"->"\[Placeholder]");


Evaluate@Table[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\),{\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}] = \[DoubleStruckG]Mat;
\[DoubleStruckG]uuMat = Inverse@\[DoubleStruckG]Mat//Simp;
Evaluate@Table[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Mu]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\),{\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}] = \[DoubleStruckG]uuMat;
\[DoubleStruckG][] = Det[\[DoubleStruckG]Mat]//Simp;


Module[{\[Sigma],\[Eta],\[Lambda],\[Mu],\[Alpha],\[Beta]}, (* Protect those variables in case the users give meaning to them. *)
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]_", "", ""},
{"", "\[Mu]_", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) := \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) =\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{" ", "\[CapitalGamma]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Nu]", "\[Mu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Sigma]\), \(\[DoubleStruckX]\)]\ \(
\*FractionBox[\(1\), \(2\)]\ \*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Sigma]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\ \((
\*SubscriptBox[\(\[PartialD]\), \(\[Mu]\)]\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Sigma]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\  + \ 
\*SubscriptBox[\(\[PartialD]\), \(\[Nu]\)]\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Sigma]", "\[Mu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\  - \ 
\*SubscriptBox[\(\[PartialD]\), \(\[Sigma]\)]\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False])\)\)\)];
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]_", "", "", ""},
{"", "\[Mu]_", "\[Sigma]_", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):= \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", "", ""},
{"", "\[Mu]", "\[Sigma]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = -(\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", "", ""},
{"", "\[Mu]", "\[Sigma]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Nu]\)]\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Sigma]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) - \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Sigma]\)]\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) + \!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Eta]\), \(\[DoubleStruckX]\)]\ \((\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Eta]", "", ""},
{"", "\[Mu]", "\[Sigma]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False] \*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Eta]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\  - \ \*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Eta]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False] \*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Eta]", "\[Sigma]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False])\)\)]);
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", "", "", ""},
{"\[Rho]_", "\[Mu]_", "\[Sigma]_", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):= \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", "", "", ""},
{"\[Rho]", "\[Mu]", "\[Sigma]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = -(\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", "", "", ""},
{"\[Rho]", "\[Mu]", "\[Nu]", "\[Sigma]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Lambda]\), \(\[DoubleStruckX]\)]\ \(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Rho]", "\[Lambda]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False] \*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", "", ""},
{"", "\[Mu]", "\[Nu]", "\[Sigma]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)\)]);
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]_", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):= \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Nu]", "\[Mu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Lambda]\), \(\[DoubleStruckX]\)]\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{" ", "\[DoubleStruckCapitalR]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", "", ""},
{"", "\[Mu]", "\[Lambda]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)];
	\[DoubleStruckCapitalR][]:= Simp @ Sum[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Mu]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\), {\[Mu],\[DoubleStruckX]}, {\[Nu],\[DoubleStruckX]}];
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]_", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):= \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) - 1/2 \!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{" ", "\[DoubleStruckG]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) \[DoubleStruckCapitalR][] // Simp;
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]_", ""},
{"", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):= \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Mu]\), \(\[DoubleStruckX]\)]\ \(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Mu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\ \*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)\)];
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]_", "\[Nu]_"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):=\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{" ", "\[DoubleStruckCapitalG]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Mu]\), \(\[DoubleStruckX]\)]\ \(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Nu]", "\[Mu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\ \*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Mu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)\)];
	\[DoubleStruckCapitalX][\[Phi]_]:= (Col=Col~Union~{\[Phi],Derivative[__][\[Phi][[0]]][Sequence@@\[Phi]]}; -Sum[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Mu]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Mu]\)]\[Phi]\) \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Nu]\)]\[Phi]\),{\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}]/2//Simp);
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]_", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]_", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):=\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)= -\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)Sum[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Alpha]", "\[Beta]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)\!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Alpha]\)]\[Phi]\) \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Beta]\)]\[Phi]\),{\[Alpha],\[DoubleStruckX]},{\[Beta],\[DoubleStruckX]}]/2 - \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)V[\[Phi]] + \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Mu]\)]\[Phi]\) \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Nu]\)]\[Phi]\);
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]_", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]_", ""},
{"", "\[Nu]_"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):= \!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Mu]\), \(\[DoubleStruckX]\)]\ \(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Mu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\ \*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)\)];
	\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]_", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]_", "\[Nu]_"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\):=\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{" ", 
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]", "]"}]}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) = Simp[\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(\[Mu]\), \(\[DoubleStruckX]\)]\ \(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Nu]", "\[Mu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\ \*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{"\[DoubleStruckCapitalT]", "[", "\[Phi]", "]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Mu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)\)];
	(* Box operator actting on scalar only. (Note GRE doesn't know if a quantity is a scalar.) *)
	SBox[\[Phi]_]:= Sum[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Mu]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) (\!\(\*
TagBox[GridBox[{
{"\[PartialD]", 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10], GridBox[{
{"\[Phi]"}
},
Selectable->True]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRED",
Selectable->False]\) - Sum[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\) \!\(
\*SubscriptBox[\(\[PartialD]\), \(\[Lambda]\)]\[Phi]\),{\[Lambda],\[DoubleStruckX]}]), {\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}];]


Print\[CapitalGamma][]:= Do[If[Order[\[Mu],\[Nu]]>=0 && \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)=!=0, Print[HoldForm[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]," = ", \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[CapitalGamma]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "", ""},
{"", "\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]], {\[Lambda],\[DoubleStruckX]},{\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}];
Print\[DoubleStruckCapitalR]4[]:= Do[If[Order[\[Lambda],\[Mu]]>0 && Order[\[Nu],\[Rho]]>0 && Order[\[Lambda],\[Nu]]>=0 && \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", "", "", ""},
{"\[Lambda]", "\[Mu]", "\[Nu]", "\[Rho]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)=!=0, Print[HoldForm[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", "", "", ""},
{"\[Lambda]", "\[Mu]", "\[Nu]", "\[Rho]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)], " = ", \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", "", "", ""},
{"\[Lambda]", "\[Mu]", "\[Nu]", "\[Rho]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]], {\[Lambda],\[DoubleStruckX]},{\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]},{\[Rho],\[DoubleStruckX]}];
Print\[DoubleStruckCapitalR]2[]:= Do[If[Order[\[Mu],\[Nu]]>=0 && \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)=!=0, Print[HoldForm[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)], " = ", \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalR]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]], {\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}];
Print\[DoubleStruckCapitalG][]:= Do[If[Order[\[Mu],\[Nu]]>=0 &&\!\(\*
TagBox[GridBox[{
{GridBox[{
{
RowBox[{" ", "\[DoubleStruckCapitalG]"}]}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)=!=0, Print[HoldForm[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)], " = ", \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"", ""},
{"\[Mu]", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]], {\[Mu],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}];
Print\[DoubleStruckCapitalG]ud[]:=Do[If[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)=!=0, Print[HoldForm[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)], " = ", \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", ""},
{"", "\[Nu]"}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]], {\[Lambda],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}];
Print\[DoubleStruckCapitalG]uu[]:=Do[If[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)=!=0, Print[HoldForm[\!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)], " = ", \!\(\*
TagBox[GridBox[{
{GridBox[{
{"\[DoubleStruckCapitalG]"}
},
Selectable->True], 
StyleBox[GridBox[{
{"\[Lambda]", "\[Nu]"},
{"", ""}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}},
Selectable->True],
FontSize->10]}
},
GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.]}, Offset[0.2]}, "RowsIndexed" -> {}}],
"GRETsr",
Selectable->False]\)]], {\[Lambda],\[DoubleStruckX]},{\[Nu],\[DoubleStruckX]}];


CalcEom::usage:="calcEom[lag,v] calcualtes the variatioin principle for Lagrangian lag, wrt variable v."
CalcEom[lag_,v_]:=Module[{d,ep,l1,l1ibp},
	l1=Expand@Coefficient[#,ep,1]&@Series[lag/.{Derivative[n__][v][x__]:>Derivative[n][v][x]+ep*Derivative[n][d][x],v[x__]:>v[x]+ep*d[x],v:>v+ep*d},{ep,0,1}];
	l1ibp=l1 /. { f_*Derivative[n__][g_][x__]/;FreeQ[f,d]&&!FreeQ[g,d] :> (-1)^Total@{n}*D[f, Sequence@@Transpose@{{x},{n}}]*g[x] };
	-l1ibp/.{d[x__]->1,d->1}//Simp]


CollectD::usage:="CollectD[expr] collects derivatives using the rules defined in cond."
CollectD[expr_]:= Module[{f, cond, vars, ass}, 
	cond = {
		Derivative[0,2,0,0][f]@@\[DoubleStruckX] + Derivative[0,0,2,0][f]@@\[DoubleStruckX] + Derivative[0,0,0,2][f]@@ \[DoubleStruckX] == \[CapitalSampi]["ii"][f]@@\[DoubleStruckX]};
	vars = Union@Cases[expr, Derivative[__][e_][__] :> e, {0,Infinity}];
	ass = And @@ Flatten[cond /. (f -> # & /@ vars)];
	Simplify[expr, ass]]
